services:
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
    - discovery.type=single-node
    ports:
    - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.14.2
    depends_on:
    - elasticsearch
    ports:
    - '5601:5601'

  logstach:
    image: logstash:7.14.2
    ports:
    - '5000:5000'
    - '5140:5140'
    volumes:
      - ./logstash_pipeline/:/usr/share/logstash/pipeline
